### ISSUE TITLE
EQ resets itself

### ISSUE THREAD

**Issue by recallmenot** [wastis/PulseEqualizerGui#3]
Hi,
so I installed on OSMC latest on Vero4k+ and the following happens:
1.) I start music playback
2.) I adjust EQ
3.) I stop music playback
4.) EQ profile is reset
I'm using Meizu HiFi USB DAC (wayy better quality than built-in audio output), volume control works fine.
Can you please help me solve this?

**Comment by wastis** [comment]
When exactly did you switch the equalizer on? On first start, it can happen that the script does not know the output device, and thus does not correctly initialize. This is only on first start. 
Maybe try
1: equalizer off
2: start playback
3: equalizer on
4: adjust EQ

**Comment by recallmenot** [comment]
So yesterday I've played around with it some more,
restarting didn't help, basically the EQ settings stick only as long as there is something playing back, as soon as playback stops it resets.
when I have nothing playing back, I set an EQ profile, then open the profile again and it's gone.
maybe it's a permissions issue? I did run the osmc install script with straight `sudo` as `sudo -u osmc` didn't work.
What files are involved in storing settings?

**Comment by wastis** [comment]
Hm, I need to think a bit more about it, in the meantime, have you tried to insert the predefined profiles?
There should be at least two files under /home/osmc/.kodi/userdata/addon_data/script.pulseequalizer.gui
1: config.json  
this file stores the frequency settings per audio device
2: profiles.json
this file stores the frequency settings per profile

And then there is the typical settings.xml, which stores the settings from the addon's settings page.

**Comment by wastis** [comment]
OK, I found the problem. 
It is actually a minor problem in the equalizer-addon, which does not store the eq-settings in the "default" profile, as this profile does not exist. 

As a quick work around, insert the predefined profiles, and select the Flat profile. Then it should remember the eq-changes within this profile.

**Comment by wastis** [comment]
I did create a new version of PulseEqualizerGui (2.2.1) that includes a proper "Default", this resolves this problem. It would be great if you could test this. (from the main, not the repository)

wget https://github.com/wastis/PulseEqualizerGui/archive/refs/heads/main.zip 

On confirmation, I will update the repository accordingly.

**Comment by wastis** [comment]
resolved with version 2.2.1
